root
    if
        if
            a_gt_b
        then
            a_sub_b
        else
            false
    then
        path-root-then
    else
        if
            xx
        then
            path-root-else-then
        else
            path-root-else-else
